### ISSUE TITLE
InvalidArgumentException

### ISSUE THREAD

**Issue by leostereo** [yaroslavche/tdlib-bundle#1]
Hi guys after cloning , tryed to build doing:
```
composer require yaroslavche/tdlib-bundle
```
But , have following response:
```
Could not find a version of package yaroslavche/tdlib-bundle matching your minimum-stability (stable). Require it wit  
  h an explicit version constraint allowing its desired stability.  
```

**Comment by yaroslavche** [comment]
Because haven't releases yet. This project is just for example.
```
composer require yaroslavche/tdlib-bundle:@dev
```
or
```
composer require yaroslavche/tdlib-bundle:dev-master
```
should work

**Comment by leostereo** [comment]
Now it says:
Root package 'yaroslavche/tdlib-bundle' cannot require itself in its
composer.json

**Comment by yaroslavche** [comment]
You clone this repository? You shouldn't. Need init composer project in empty directory
```
$ composer init
```
follow instructions and then run
```
composer require yaroslavche/tdlib-bundle
```

**Comment by leostereo** [comment]
yes, I was doing wrong ; now it is working.
It is very nice , the html using vue you created.
thanks for your help, and for the video.
Leandro.
